### ISSUE TITLE
[feature] Saltstack support

### ISSUE THREAD

**Issue by ngortheone** [vermut/intellij-snakeyaml#14]
Hi 

I am willing to give some help improving this plugin for saltstack syntax support (jinja and yaml). But I am new to writing idea plugins. Could you share any ideas where to start applying my enthusiasm?

**Comment by vermut** [comment]
Well.. This is not an easy part. Actually Jinja is on top of the Yaml. 
In my plans there should a Jinja template engine doing the first pass and then giving clean code to underlying Yaml.

The good place to investigate would be [Handlebars plugin](https://github.com/JetBrains/intellij-plugins/tree/master/handlebars). It has nice pieces of code to study. But without documentation from JetBrains it's all trial and error.

My previous project [IntelliJ-Ansible](https://github.com/vermut/intellij-ansible/) had the previous approach - parsing Yaml AND Jinja in one plugin. It's also available in plugin repository. If you are looking for some quick fixed instead implementing whole template layer you may dig there.
